### PR TITLE
Build also on Windows

### PR DESCRIPTION
**Pull request by mhujer**

### CODE REVIEW

**Comment by mhujer** [comment]
Surprisingly, even the setup from phpstan/phpstan-src does not work (and it fails there as well)

**Comment by ondrejmirtes** [comment]
I hope it's just a temporary downtime ((503) Server Unavailable. Service Unavailable) and it will resolve itself.

**Comment by mhujer** [comment]
It seems [they are having trouble at Chocolatey](https://status.chocolatey.org/), I will update the PR when they are resolved.

image

**Comment by mhujer** [comment]
It seems to be working fine now.

**Comment by ondrejmirtes** [comment]
Thank you 😊

**Pull request merged**
