### PR TITLE
GetRepositoryDynamicReturnTypeExtension: improved return type when argument is not recognized

### PR DESCRIPTION
**Pull request by pepakriz**
Previously this bug hasn't been detected:

```php
	/**
	 * @param class-string $entityName
	 */
	public function doSomethingWithEntity(string $entityName): void
	{
		$repository = $this->entityManager->getRepository($entityName);
		$repository->createQueryBuilder('a')->unknownMethod(); // bug
```

### CODE REVIEW

**Comment by pepakriz** [comment]
@ondrejmirtes 
1) `Doctrine\Persistence\ObjectRepository<T>`
2) Ok, done

**Comment by ondrejmirtes** [comment]
Unresolved `T` in this context is wrong - `ObjectRepository<T>`. You're passing a `class-string` so you should get `ObjectRepository<mixed>` or `ObjectRepository<object>` at best..

**Comment by ondrejmirtes** [comment]
I believe you so for now I reverted the change released it as 0.12.9. The stubs should work for everyone again.

You'll be able to install dev-master and reproduce this problem so we can return to simplified and thinner stub files again when we fix this problem.

**Comment by ondrejmirtes** [comment]
Oh, wrong thread.

**Comment by pepakriz** [comment]
@ondrejmirtes ok, check the second commit.

**Comment by ondrejmirtes** [comment]
Thank you! I modified the solution in your second commit to let PHPStan do the logic: https://github.com/phpstan/phpstan-doctrine/commit/5762a215be4a06206ee4cd62df24da3196ebdcc9

**Comment by ondrejmirtes** [comment]
I'll be able to release this once #101 is solved.

**Pull request merged**
