### PR TITLE
Add support for magic find* entity repository methods #35

### PR DESCRIPTION
**Pull request by jackbentley**

### CODE REVIEW

**Comment by keelerm84** [comment]
I believe this PR would also fix some issues I'm having. If the tests were passing, would this likely get merged?

**Comment by jackbentley** [comment]
Thanks for the comment 😄 I've fixed the tests - was just CS issues.

**Comment by ondrejmirtes** [comment]
Hi, this PR does not take full advantage of static analyser - ideally, it should know which exact `findBy` methods exist. It should be possible once the entity metadata are available from other PRs.

**Comment by jackbentley** [comment]
I agree, @ondrejmirtes. I wanted to implement that behaviour but wasn't able to easily achieve it. Hopefully, that's something that can be improved when the API becomes available?

**Comment by ondrejmirtes** [comment]
Hi, this will need to be reworked in light of #49 - it will allow you to find out which `findBy` methods are really there based on the entity :)

**Comment by ondrejmirtes** [comment]
Thanks! I'll implement the checks as a rule.

**Comment by ondrejmirtes** [comment]
Implemented the rest: https://github.com/phpstan/phpstan-doctrine/commit/5bf58a32e0c056ee9abaca114e6109ee4ed0aa79

**Pull request merged**
