### PR TITLE
Allow for final embeddable class

### LINKED ISSUE #215: EntityNotFinalRule should allow for final keyword for embeddables
## State

Project with some entities and embeddables.

## Current

```
 ------ -------------------------------------------------------------------------------------------- 
  Line   src/Entity/Bar.php                                                                      
 ------ -------------------------------------------------------------------------------------------- 
  10     Entity class App\Foo\Entity\Bar is final which can cause problems with proxies.  
 ------ -------------------------------------------------------------------------------------------- 
```

## Expected

No errors :)

### PR DESCRIPTION
**Pull request by akondas**
Fixes #215

### CODE REVIEW

**Review by marmichalski — APPROVED** [review]

**Comment by ondrejmirtes** [comment]
Perfect, thank you!

**Comment by ondrejmirtes** [comment]
https://github.com/phpstan/phpstan-doctrine/releases/tag/1.3.8

**Comment by akondas** [comment]
Wow, @ondrejmirtes :beers: that was crazy fast. Big big thank you.

**Comment by dgafka** [comment]
Impressive response time, great! :)

**Pull request merged**
