### PR TITLE
Narrow type of Collection::last() when using Collection::isEmpty()

### PR DESCRIPTION
**Pull request by ruudk**
Now that we have #172 , we should do the same for `last()`.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thank you :)

**Comment by ruudk** [comment]
⚡ Would be great to have this tagged too 🙏  Thanks!

**Comment by ondrejmirtes** [comment]
Tagged 👌

**Comment by VincentLanglet** [comment]
Hi @ruudk, would is be possible to do the same with the count value ?

image

**Comment by ruudk** [comment]
Not sure if that's possible TBH. /cc @ondrejmirtes

**Comment by ondrejmirtes** [comment]
Just assert that last() is not null instead...

**Comment by VincentLanglet** [comment]
> Just assert that last() is not null instead...

I know, and that's what 'im doing.
But the same argument could have be use for `isEmpty`, and still this great improvement was made.

If I assert that the count is > 0, I could avoid to add another assert that last/first is not false.

Would it be implementable ?

**Comment by ondrejmirtes** [comment]
Nope, the TypeSpecifyingExtension API doesn’t allow it.

**Pull request merged**
