### PR TITLE
Allow to use both ORM and ODM

### PR DESCRIPTION
**Pull request by VincentLanglet**
Might solve https://github.com/phpstan/phpstan-doctrine/issues/53#issuecomment-936667144
I need to check tomorrow.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> I need a test here so I can understand what are the ramifications.

I added one. Don't hesitate if you need more explanation or the test to be presented differently, because it wasn't easy to me to reproduce my issue.

If you implement your own ObjectManager in order to support both ORM and ODM depending on the class of the entity, you need the repository class to also depends on the entities. The object manager is correctly finding the classmetadata, so if the entity/document has a custom repository there is no issues. But in case there is not, prior to these change the default value was always the same repository and it could depend on the classmetadata.

I think it won't impact the perf of basics users since `??` has basically no cost, and it works for me (and for the tests).

**Comment by VincentLanglet** [comment]
Friendly ping @ondrejmirtes. Do you have time to take a look ? This would help me to migrate on phpstan 1 :)

**Comment by ondrejmirtes** [comment]
@VincentLanglet  My top priority right now is PHP 8.1 support (https://phpstan.org/blog/plan-to-support-php-8-1). The main action is now happening in https://github.com/ondrejmirtes/BetterReflection/tree/ng and https://github.com/phpstan/phpstan-src/tree/ng-better-reflection. Once this is finished and released, the operations will return to normal eventually. I now have 187 emails in my inbox worthy of my attention (all related to PHPStan), so please stay tuned.

**Comment by ondrejmirtes** [comment]
I'm gonna fix it myself, stay tuned.

**Comment by VincentLanglet** [comment]
Just saw that `getResolvedRepositoryClass` is only returning DocumentRepository when an objectManager was provided
https://github.com/phpstan/phpstan-doctrine/blob/master/src/Type/Doctrine/ObjectMetadataResolver.php#L163-L167 which is currently the blocking point.

Feel free to ping me if you want that I test your branch

**Pull request closed without merging**
