### PR TITLE
Update AbstractQuery.stub

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
The test failures are unrelated to my patch.

**Comment by enumag** [comment]
@ondrejmirtes Can you merge this please? Because of the current impossibility to override a stub on my side it's currently kinda blocking me.

**Comment by ondrejmirtes** [comment]
Thank you.

**Comment by enumag** [comment]
Thanks!

**Comment by stof** [comment]
This breaks things when using `INDEX BY` in DQL, as the result is not a list in such case. Returning a list is something that needs to be handled by improving the type extension analysing the query, not by this broken stub

**Comment by enumag** [comment]
I see. Didn't know that. Alright let's revert this and handle it better.

**Comment by VincentLanglet** [comment]
There is the wip https://github.com/phpstan/phpstan-doctrine/pull/384

**Comment by enumag** [comment]
@VincentLanglet That PR only handles object result while my case is for array result but it does the hard work of detecting the list result. I should be able to fix this correctly after that PR is merged.

**Pull request merged**
