### PR TITLE
Bump doctrine dependencies

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hey, I plan to work on this myself, make sure not to waste any effort here :)

**Comment by VincentLanglet** [comment]
> Hey, I plan to work on this myself, make sure not to waste any effort here :)

Do you need any help on this ?

I would say that all tests should have both annotations and attributes to work with both old and new versions.
So I can try to add them when I have time.

**Comment by ondrejmirtes** [comment]
I have different ideas but I need to verify them myself.

**Comment by VincentLanglet** [comment]
> I have different ideas but I need to verify them myself.

Ok, I'll stop for now then. Ping me if I can help.

**Comment by VincentLanglet** [comment]
> I have different ideas but I need to verify them myself.

I still wanted to try my strategy and I went from 100+ errors to around 20 currently,
by using both attributes and annotations everywhere.

I can keep going and trying to solve as possible errors that I can @ondrejmirtes

**Comment by ondrejmirtes** [comment]
Please don't. I'm working ob this myself. In the end we can compare our approaches 😊

**Comment by VincentLanglet** [comment]
> Please don't. I'm working ob this myself. In the end we can compare our approaches 😊

Ok, I'll wait 😊

**Comment by ondrejmirtes** [comment]
So this is my work in progress:

* https://github.com/phpstan/phpstan-doctrine/pull/532
* https://github.com/phpstan/phpstan-doctrine/pull/533
* https://github.com/phpstan/phpstan-doctrine/pull/534
* https://github.com/phpstan/phpstan-doctrine/pull/535

**Pull request closed without merging**
