### PR TITLE
add stub for EntityManager::getClassMetadata

### PR DESCRIPTION
**Pull request by Khartir**
Copied from https://github.com/doctrine/orm/blob/8291a7f09b12d14783ed6537b4586583d155869e/lib/Doctrine/ORM/EntityManagerInterface.php#L337-L344

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
What do these changes achieve please? Can you please add a test that fails without these changes? Thanks.

**Comment by Khartir** [comment]
The problem is code like this:
```php
/**
 * @template T of object
 * @template-extends EntityRepository<T>
 */
class IntermediateRepository extends EntityRepository
{
	/**
	 * @param ClassMetadata<T> $class
	 */
	public function __construct(EntityManagerInterface $em, ClassMetadata $class)
	{
		parent::__construct($em, $class);
	}
}

/**
 * @extends IntermediateRepository<MyEntity>
 */
class MyRepository extends IntermediateRepository
{
	public function __construct(
		EntityManagerInterface $manager
	) {
		parent::__construct($manager, $manager->getClassMetadata(MyEntity::class));
	}
}
```
This fails with `Parameter #2 $class of method IntermediateRepository<MyEntity>::__construct() expects Doctrine\ORM\Mapping\ClassMetadata<MyEntity>, Doctrine\ORM\Mapping\ClassMetadata<object> given.`

With the extension of the stub this now works, but I'm having trouble writing a test for this.

**Comment by Khartir** [comment]
OK writing a test for this wasn't that hard after all, I was just missing an import. :laughing:

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
