### PR TITLE
Pass allowNullablePropertyForRequiredField to EntityRelationRule

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @ondrejmirtes, this is a follow up of the option introduced in https://github.com/phpstan/phpstan-doctrine/pull/208
The option is working properly for properties but to me the same behavior is expected for OtO, OtM, ...

**Comment by ondrejmirtes** [comment]
Is this solving a real-world problem when using entities as form DTOs?

**Comment by VincentLanglet** [comment]
> Is this solving a real-world problem when using entities as form DTOs?

Sure, for instance I have those errors in my work project.
The option introduced solved 95% of the "property might be null, but database is not",
but I still have some errors with this message for OtO/MtO. This PR should fix my issue.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by VincentLanglet** [comment]
Thanks, would a release possible ? :)

**Comment by ondrejmirtes** [comment]
I've already opened 1.0-dev, the release is a few weeks out.

**Comment by VincentLanglet** [comment]
> I've already opened 1.0-dev, the release is a few weeks out.

I see, it will be 1.0 for every extensions too ; didn't think about it

**Pull request merged**
