### PR TITLE
Query type inference failures reproductions

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Alright @VincentLanglet, here's one:

```
--- Expected
+++ Actual
@@ @@
-'list<array{id: int}>'
+'list<array{id: int|numeric-string|null}>'
```

**Comment by VincentLanglet** [comment]
> Alright @VincentLanglet, here's one:
> 
> ```
> --- Expected
> +++ Actual
> @@ @@
> -'list<array{id: int}>'
> +'list<array{id: int|numeric-string|null}>'
> ```

If I dump the Query, I get
```
Doctrine\ORM\Query<null, array{id: int|numeric-string|null}>
```
so `QueryResultDynamicReturnTypeExtension` works fine but the issue seems to be with `QueryResultTypeWalker`

This is a consequence of https://github.com/phpstan/phpstan-doctrine/pull/273 (cc @arnaud-lb)
and there is the following test case.
```
'identity function' => [
				$this->constantArray([
					[new ConstantIntegerType(1), TypeCombinator::addNull($this->numericStringOrInt())],
					[new ConstantIntegerType(2), $this->numericStringOrInt()],
					[new ConstantIntegerType(3), TypeCombinator::addNull($this->numericStringOrInt())],
					[new ConstantIntegerType(4), TypeCombinator::addNull(new StringType())],
					[new ConstantIntegerType(5), TypeCombinator::addNull(new StringType())],
					[new ConstantIntegerType(6), TypeCombinator::addNull($this->numericStringOrInt())],
					[new ConstantIntegerType(7), TypeCombinator::addNull(new MixedType())],
					[new ConstantIntegerType(8), TypeCombinator::addNull($this->numericStringOrInt())],
				]),
				'
					SELECT		IDENTITY(m.oneNull),
								IDENTITY(m.one),
								IDENTITY(m.oneDefaultNullability),
								IDENTITY(m.compoundPk),
								IDENTITY(m.compoundPk, \'id\'),
								IDENTITY(m.compoundPk, \'version\'),
								IDENTITY(m.compoundPkAssoc),
								IDENTITY(m.compoundPkAssoc, \'version\')
					FROM		QueryResult\Entities\Many m
				',
			],
```

I'll need to investigate why `numericStringOrInt` is used

**Comment by VincentLanglet** [comment]
I identified that the `numeric-string` is because of the following code
https://github.com/phpstan/phpstan-doctrine/blob/a1ba4549d2f4167adae5a91871b0fc88fe66240d/src/Type/Doctrine/Query/QueryResultTypeWalker.php#L837-L855

**Comment by VincentLanglet** [comment]
I try finding some "solutions" for this issue.

But I discovered a new one.
```
$result = $this->entityManager->createQueryBuilder()
			->select('p.id AS id')
			->from(OrderItem::class, 'oi')
			->join('oi.product', 'p')
			->getQuery()
			->getArrayResult();
		assertType('list<array{id: int}>', $result);
```
Works

```
$result = $this->entityManager->createQueryBuilder()
			->select('p.id AS id')
			->from(OrderItem::class, 'oi')
			->leftJoin('oi.product', 'p')
			->getQuery()
			->getArrayResult();
		assertType('list<array{id: int|null}>', $result);
```
Also works But
```
$result = $this->entityManager->createQueryBuilder()
			->select('p.id AS id')
			->from(OrderItem::class, 'oi')
			->leftJoin('oi.product', 'p')
			->where('p.id IS NOT NULL')
			->getQuery()
			->getArrayResult();
		assertType('list<array{id: int}>', $result);
```
doesn't.

The `where` condition are not supported, and this may be too complicated to support them.

So far, I think I'll have to change every Union to BenevolentUnion then...

**Comment by VincentLanglet** [comment]
I will need your opinion on this solution @ondrejmirtes https://github.com/phpstan/phpstan-doctrine/pull/447

**Comment by ondrejmirtes** [comment]
Continued in https://github.com/phpstan/phpstan-doctrine/pull/593

**Pull request closed without merging**
