### PR TITLE
Query: add test for some method calls

### PR DESCRIPTION
**Pull request by janedbal**

### CODE REVIEW

**Comment by janedbal** [comment]
Hm, this is probably not a proper fix. This is more generic issue. Looks like it is related to all methods that are overwritten in Query and use `{@inheritdoc}`.

**Comment by janedbal** [comment]
Changed to failing test till I find the issue.

**Comment by janedbal** [comment]
Looks like related to https://github.com/phpstan/phpstan/issues/6462

**Comment by janedbal** [comment]
This should fix it: https://github.com/phpstan/phpstan-src/pull/2803

**Comment by ondrejmirtes** [comment]
Please test this after your merged PR https://github.com/phpstan/phpstan-src/pull/2803 is released :)

**Comment by janedbal** [comment]
It works, do you want to bump phpstan version in composer just to have this merged?

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
