### PR TITLE
Resolve entity metadata without objectManagerLoader

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
https://github.com/phpstan/phpstan-doctrine/commit/670e28dfa49f8c5007677aca53709c0f90713edb ;)

**Comment by VincentLanglet** [comment]
> [670e28d](https://github.com/phpstan/phpstan-doctrine/commit/670e28dfa49f8c5007677aca53709c0f90713edb) ;)

Thanks.

I tried the master branch on my project and I have some issues that I don't have with my customObjectManager (cf https://github.com/phpstan/phpstan-doctrine/pull/218).

```
$queryBuilder = $this->getDocumentManager()->getRepository(LogDocument::class)->createQueryBuilder();
```
Method Doctrine\ORM\EntityRepository<App\Document\LogDocument>::createQueryBuilder() invoked with 0 parameters, 1-2 required.

Here the Repository should be considered as a `Doctrine\ODM\MongoDB\Repository`. I have the same error for multiple Document.

```
$expeditions = $this->getEntityManager()->getRepository(Expedition::class)->getListOrders($context, $date);
```
Call to an undefined method Doctrine\ORM\EntityRepository<App\Entity\Expedition>::getListOrders(). Weird thing, I only have the issue with the repository of the Expedition class...

What can I do to help to debug this ?

**Comment by ondrejmirtes** [comment]
What's gonna help me here is:

```php
\PHPStan\dumpType($this->getDocumentManager());
\PHPStan\dumpType($this->getDocumentManager()->getRepository(LogDocument::class));
```

What's the actual output and what's the expected output?

**Comment by ondrejmirtes** [comment]
And about Expedition - where is the `getListOrders` method defined, and does the `Expedition` entity have a `repositoryClass` setting in `@ORM\Entity`?

**Comment by VincentLanglet** [comment]
> What's gonna help me here is:
> 
> ```
> \PHPStan\dumpType($this->getDocumentManager());
> \PHPStan\dumpType($this->getDocumentManager()->getRepository(LogDocument::class));
> ```
> 
> What's the actual output and what's the expected output?

145    Dumped type: Doctrine\ODM\MongoDB\DocumentManager                                                                              
  146    Dumped type: Doctrine\ORM\EntityRepository<App\Document\LogDocument>    

Expected type would be `'Doctrine\ODM\MongoDB\Repository\DocumentRepository'`

IMHO, it's the same issue that I was trying to solve in https://github.com/phpstan/phpstan-doctrine/pull/218/files#diff-2ffdfff3ded45d084e0d7d312fe16939835dba7dcad8fabc12a2c3ece495b46aR113-R124

Since I use both ORM and ODM, I shouldn't fallback on `$this->getResolvedRepositoryClass();` because I have a fallback for ORM and a fallback for ODM ; but phpstan only save the first one met (EntityRepository) in the `getResolvedRepositoryClass` method.

**Comment by ondrejmirtes** [comment]
Yeah, this is definitely doable, I'm gonna fix it.

**Comment by VincentLanglet** [comment]
```
        $listProductAsset = $this->getEntityManager()->getRepository(Asset::class)->findAllByProductId(1);
        $expeditions = $this->getEntityManager()->getRepository(Expedition::class)->getListOrders($context, $date);

        \PHPStan\dumpType($this->getEntityManager());
        \PHPStan\dumpType($this->getEntityManager()->getRepository(Asset::class));
        \PHPStan\dumpType($this->getEntityManager()->getRepository(Expedition::class));
```
is giving me
```
  43     Call to an undefined method Doctrine\ORM\EntityRepository<App\Entity\Expedition>::getListOrders().  
  45     Dumped type: App\Core\Doctrine\ORM\EntityManager                                                    
  46     Dumped type: App\Repository\AssetRepository<App\Entity\Asset>                                       
  47     Dumped type: Doctrine\ORM\EntityRepository<App\Entity\Expedition> 
```

Expedition has the phpdoc 
```
/**
 * @ORM\Table(name="tbl_expedition")
 * @ORM\Entity(repositoryClass="App\Repository\ExpeditionRepository")
 */
class Expedition extends BaseEntity implements EntityInterface
```

But I found that the issue is related to `Embeddable`. I have a field 
```
/**
 * @ORM\Embedded(class="App\Entity\Embeddable\Slot")
 */
private ?Slot $slot = null;
```

Removing it fix my issue. Should I open an issue ?

**Comment by ondrejmirtes** [comment]
Yeah, definitely open an issue.

**Comment by ondrejmirtes** [comment]
This should be fine: https://github.com/phpstan/phpstan-doctrine/commit/f66919f06d4005f3400e9558e471851bada6eb94

Please note the new different ormRepositoryClass / odmRepositoryClass config parameters for setting base repository classes if you have one.

**Comment by VincentLanglet** [comment]
> This should be fine: [f66919f](https://github.com/phpstan/phpstan-doctrine/commit/f66919f06d4005f3400e9558e471851bada6eb94)
> 
> Please note the new different ormRepositoryClass / odmRepositoryClass config parameters for setting base repository classes if you have one.

Thanks,  it does work for me.

**Pull request merged**
