### PR TITLE
Add integration tests for ODM features

### PR DESCRIPTION
**Pull request by lcobucci**
Which kicks-off the support for #26 

Depends on #38

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I'm not able to try this out because of:

```
  Problem 1
    - alcaeus/mongo-php-adapter 1.1.x-dev requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.5 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for alcaeus/mongo-php-adapter ^1.1 -> satisfiable by alcaeus/mongo-php-adapter[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.x-dev].
```

I think it shouldn't be necessary to have installed `mongodb` extension in order to develop this package. What is it exactly required for?

**Comment by alcaeus** [comment]
Because of the tests: they need to import ODM classes. You could remove the dependency, skip the tests if ODM isn’t installed and only install it on travis. However, as changing something might break ODM functionality, I would recommend to keep this as is. This extension is supposed to cover ORM and ODM, so it’s expected to have both as a dev dependency.

**Comment by ondrejmirtes** [comment]
Is it just because of some `use` or `::class` or is actually some code from alcaeus/mongo-php-adapter executed?

**Comment by mcfedr** [comment]
All the tests run fine if I remove `alcaeus/mongo-php-adapter` from composer.json, and without mongodb installed

**Comment by alcaeus** [comment]
> All the tests run fine if I remove `alcaeus/mongo-php-adapter` from composer.json, and without mongodb installed

Correct, because you're pretending that the `mongo` extension is installed. You can skip the adapter package until you actually start using the ODM classes, at which point they'll fail if they can't find the classes you pretend are there.

**Comment by ondrejmirtes** [comment]
Superceded by #48.

**Pull request closed without merging**
